# File: docker-compose.yml
# Author: Marc Bria UAB (marc.bria@uab.es)

services:
  db:
    image: ${DB_VERSION:-mariadb:11.8}
    env_file:
      - .env
    container_name: "pkp_db_${COMPOSE_PROJECT_NAME}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-changeMePlease}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-pkp}"
      MYSQL_USER: "${MYSQL_USER:-pkp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-changeMePlease}"
#    volumes:
#      - ./volumes/db:/var/lib/mysql
#      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
#      - ./volumes/db-import:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: unless-stopped

  app:
    image: ${IMAGE_SOURCE}/${PKP_TOOL}:${PKP_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Modify .env to change this arguments
        PKP_TOOL: ${PKP_TOOL}
        PKP_VERSION: ${PKP_VERSION}
        WEB_SERVER: ${WEB_SERVER}
        BUILD_PKP_APP_OS: ${BUILD_PKP_APP_OS}
    env_file:
      - .env
    container_name: "pkp_app_${COMPOSE_PROJECT_NAME}"
    hostname: "${COMPOSE_PROJECT_NAME}"
    entrypoint: ["/docker-entrypoint.sh"]
    ports:
      - ${HTTP_PORT:-8081}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      # Keep host and container sync:
      - /etc/localtime:/etc/localtime
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      - ./volumes/logs/app:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
      - ./volumes/config/pkp.config.inc.php:/var/www/html/config.inc.php:ro
      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess:ro
      - ./volumes/config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro

    networks:
      - inside
    depends_on:
      - db
    restart: unless-stopped

networks:
  inside:
    external: false
